# Generated by Django 3.1.1 on 2021-06-12 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=50, unique=True)),
                ('transaction_status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('close', 'close')], max_length=200)),
                ('remarks', models.CharField(max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.branchmaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.companyledgermaster')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.departmentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=5)),
                ('rate', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('metre', 'metre')], max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.articlemaster')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.colormaster')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_quantity', models.DecimalField(decimal_places=4, max_digits=5)),
                ('net_quantity', models.DecimalField(decimal_places=4, max_digits=5)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('metre', 'metre')], max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.articlemaster')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.colormaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.companyledgermaster')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.transactionlineitem')),
            ],
        ),
    ]
