# Generated by Django 3.1.1 on 2021-07-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=10)),
                ('transaction_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Close', 'Close')], max_length=15)),
                ('remarks', models.CharField(default=None, max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transaction_branch', to='transaction.branchmaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transaction_company', to='transaction.companyledgermaster')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transaction_department', to='transaction.departmentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_on_date', models.DateTimeField()),
                ('qunatity', models.DecimalField(decimal_places=10, max_digits=19)),
                ('rate_per_unit', models.IntegerField()),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('Metre', 'Metre')], max_length=5)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transaction_article', to='transaction.articlemaster')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transaction_color', to='transaction.colormaster')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transaction.transactiontable')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_quantity', models.DecimalField(decimal_places=10, max_digits=19)),
                ('net_quantity', models.DecimalField(decimal_places=10, max_digits=19)),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('Metre', 'Metre')], max_length=5)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inven_article', to='transaction.articlemaster')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inven_color', to='transaction.colormaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inven_company', to='transaction.companyledgermaster')),
                ('transaction_line_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transaction.transactionlineitem')),
            ],
        ),
    ]
