# Generated by Django 3.1.1 on 2021-07-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=50)),
                ('transaction_status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('CLOSE', 'CLOSE')], max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tn_branch', to='transaction.branchmaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tn_company', to='transaction.companyledgermaster')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tn_department', to='transaction.departmentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLineItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_on_date', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=15)),
                ('rate_per_unit', models.IntegerField()),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('METRE', 'METRE')], max_length=12)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='td_article', to='transaction.articlemaster')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='td_colour', to='transaction.colormaster')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tr_item_detail', to='transaction.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_quantity', models.DecimalField(decimal_places=10, max_digits=15)),
                ('net_quantity', models.DecimalField(decimal_places=10, max_digits=15)),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('METRE', 'METRE')], max_length=12)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invent_article', to='transaction.articlemaster')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invent_colour', to='transaction.colormaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invent_company', to='transaction.companyledgermaster')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transaction.transactionlineitemdetail')),
            ],
        ),
    ]
